---
- name: Install Biopython for pipeline import
  ansible.builtin.pip:
    name: "biopython"
- name: Install Celery[redis]
  ansible.builtin.pip:
    name: "celery[redis]"
- name: Install MinIO Python client
  ansible.builtin.pip:
    name: minio
