- name: Hashicorp key
  rpm_key:
    state: present
    key: "https://rpm.releases.hashicorp.com/gpg"
  become: true
  become_user: root
- name: Hashicorp Repo
  ansible.builtin.yum_repository:
    baseurl: "https://rpm.releases.hashicorp.com/RHEL/$releasever/$basearch/stable"
    state: present
    name: "hashicorp-stable"
    description: "Hashicorp Stable Repo"
    gpgcheck: true
    gpgcakey: https://rpm.releases.hashicorp.com/gpg
  become: true
  become_user: root
- name: Terraform + Vault
  ansible.builtin.dnf:
    name:
      - terraform
#      - vault # currently this package is broken
  become: true
  become_user: root
- name: Download and install LinuxBrew üêßüçª
  shell: "curl -sfL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh | bash -"
- name: Add Linuxbrew to path.
  lineinfile:
    dest: "~/.bashrc"
    line: eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
- name: Install Kubectl, Krew, Helm
  shell: 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)" && brew install kubectl krew helm k9s minio-mc'