- name: Make directory to export
  ansible.builtin.file:
    path: /shared
    state: directory
- name: Create exports file
  template:
    src: files/exports.j2
    dest:  /etc/exports
    mode: "0644"
- name: Enable NFS server service
  ansible.builtin.service:
    name: nfs-server
    enabled: true
    state: started
- name: Run exportfs
  ansible.builtin.shell: exportfs -a
- name: Make user directory
  ansible.builtin.file:
    path: /shared/almalinux
    state: directory
    owner: almalinux
- name: Create home directory sym-link
  ansible.builtin.file:
    src: /shared/almalinux
    dest: /home/almalinux/shared
    state: link
