---
# tasks for celery worker setup
- name: Deploy celeryconfig.py  #dynamically create celeryconfig (incase ip of host changes)
  ansible.builtin.template:
    src: celeryconfig.py.j2
    dest: /shared/almalinux/scripts/celery/celeryconfig.py
    owner: almalinux
    group: almalinux
    mode: "0644"
- name: Deploy Celery worker daemon systemd unit
  become: true
  ansible.builtin.template:
    src: celery-daemon.service.j2
    dest: /etc/systemd/system/celery-daemon.service
    mode: "0644"
- name: Reload systemd daemon
  become: true
  ansible.builtin.command: systemctl daemon-reload
- name: Enable celery worker daemon service
  become: true
  ansible.builtin.service:
    name: celery-daemon
    enabled: yes
- name: Start celery worker daemon service
  become: true
  ansible.builtin.service:
    name: celery-daemon
    state: restarted

