---
- name: Host configuration
  hosts: host
  become: true
  vars:
    gitrepourl: "https://gitlab2.ds4eng.condenser.arc.ucl.ac.uk/ucabjsy/coursework-comp0235-2025.git"
  roles:
    - host_python_dependencies
    - host_files
    - host_configure_redis
    - host_configure_minio
    - host_logging
    - host_database
