---
- name: Storage configuration
  hosts: storage
  become: true
  vars:
    gitrepourl: "https://gitlab2.ds4eng.condenser.arc.ucl.ac.uk/ucabjsy/coursework-comp0235-2025.git"
  roles:
    - storage_configure_nfs
    - storage_nfs_populator
    - storage_logging
