---
# tasks for celery worker setup
#- name: Make home dir accesible by systemd
 # ansible.builtin.file:
  #  path: /home/almalinux
   # mode: '0755'
    #owner: almalinux
    #group: almalinux
- name: Deploy celeryconfig.py  #dynamically create celeryconfig (incase ip of host changes)
  ansible.builtin.template:
    src: celeryconfig.py.j2
    dest: /shared/almalinux/scripts/celery/celeryconfig.py
    owner: almalinux
    group: almalinux
    mode: "0644"
- name: Deploy Celery worker daemon systemd unit
  ansible.builtin.template:
    src: celery-daemon.service.j2
    dest: /etc/systemd/system/celery-daemon.service
    mode: "0644"
- name: Reload systemd daemon
  ansible.builtin.command: systemctl daemon-reload
- name: Enable celery worker daemon service
  ansible.builtin.service:
    name: celery-daemon
    enabled: yes
- name: Start celery worker daemon service
  ansible.builtin.service:
    name: celery-daemon
    state: restarted

